### ISSUE TITLE
Forex Exchange Rates

### ISSUE THREAD

**Issue by adamewozniak** [ojo-network/price-feeder#10]

**Comment by rbajollari** [comment]
Free Forex Providers:

1. https://polygon.io/:
- Pricing and free offerings: https://polygon.io/pricing
- Docs: https://polygon.io/docs/stocks/getting-started 
2. https://www.alphavantage.co/:
- Free api key: https://www.alphavantage.co/support/#api-key
- Docs: https://www.alphavantage.co/documentation/#
3. https://currencylayer.com/:
- Pricing and free offerings:https://apilayer.com/marketplace/currency_data-api?_gl=1*1v6oz1d*_ga*NjIwMjc5NTkzLjE2NzI3NjczMDE.*_ga_HGV43FGGVM*MTY3Mjc2NzMwMS4xLjEuMTY3Mjc2Nzg5Ni4xOS4wLjA.#pricing
- Docs:https://currencylayer.com/documentation

**Comment by adamewozniak** [comment]
@rbajollari nice! do all of these support the necessary components of our candles / tickers? 
If so, it looks like implementation will be very similar, just with more rate limiting

**Comment by rbajollari** [comment]
Upon some further inspection they all have some limitations in their free verions that might not work for us. `polygon.io` looks like the free version only gives you end of day data instead of real-time. I also just noticed that the minimum time series for exchange rate data on the free version of `alphavantage` is daily, and `currencylayer` doesn't allow time-frame queries in general for the free version. @adamewozniak I haven't come across a forex api that will offer real-time interval data for free yet. The only real-time data thats offered for free is just the rate at a given time but that would require us to calculate stuff like open, close, high, and low prices in interval ourselves by storing prices in that interval. However, even that would probably be inaccurate since the api would have a request limit which most likely wont be grannular enough.

**Comment by adamewozniak** [comment]
🤔 high LOE with largely outdated / incompatible data. Let's talk about this in our standup
